---
name: libres

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:  # <-- Esto permite ejecutarla a mano desde la interfaz web de GitHub

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  libres:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Plazas libres
        run: python ./3-web-actividades.py > public/index.html
        env:
          PLAYOFFAPIURL: ${{ secrets.PLAYOFFAPIURL}}
          PLAYOFFPASSRO: ${{ secrets.PLAYOFFPASSRO}}
          PLAYOFFUSERRO: ${{ secrets.PLAYOFFUSERRO}}

      - name: Deploy to GitHub Pages
        if: success() && github.event_name != 'pull_request'
        uses: crazy-max/ghaction-github-pages@v4.2.0
        with:
          target_branch: gh-pages
          build_dir: public
        env:
          GITHUB_TOKEN: ${{ secrets.GHA }}
